### ISSUE TITLE
Random Forests, out of bounds error with SVec add method (nondeterministic)

### ISSUE THREAD

**Issue by DanielTakeshi** [BIDData/BIDMach#100]
Hi John,

I can verify that I am running the latest version of BIDMach (I pulled about 30 minutes ago from master), also BIDMat as well (and I copied the BIDMat.jar over to BIDMach's ```lib``` directory). I'm getting an out of bounds error in the Random Forests class, in the SVec add method. The challenging part is that I cannot easily reproduce this error message.

**Context**: I am using the Files DataSource for Random Forests, and have 19 data matrices. I am using 18 of these as training, and the last matrix (the 19th) as testing. After a few iterations, I will get this message:

I modified the SVec add method by adding in three debug printlns in the while loop:

```
    while (i1 < n1 || i2 < n2) {
      if (i1 >= n1 || (i2 < n2 && inds2(i2) < inds1(i1))) {

        if (count >= inds3.length) {
          println("inds3.length=" + inds3.length + ", count=" + count)
        }    

        inds3(count) = inds2(i2);
        counts3(count) = counts2(i2);
        count += 1;
        i2 += 1;
      } else if (i2 >= n2 || (i1 < n1 && inds1(i1) < inds2(i2))) {

        if ((count >= inds3.length) || (count >= counts3.length) || (i1 >= counts1.length)) {
            println("count=" + count + ", inds3.length=" + inds3.length + ", counts3.length=" + counts3.length + ", counts1.length=" + counts1.length)
        }    

        inds3(count) = inds1(i1);
        counts3(count) = counts1(i1);
        count += 1;
        i1 += 1;
      } else {

        if ((count >= inds3.length) || (count >= counts3.length) || (i1 >= counts1.length)) {
            println("count=" + count + ", inds3.length=" + inds3.length + ", counts3.length=" + counts3.length + ", counts1.length=" + counts1.length)
        }    

        inds3(count) = inds1(i1);
        counts3(count) = counts1(i1) + counts2(i2);
        count += 1;
        i1 += 1;
        i2 += 1;
      }    
    } 
```

but other than that everything is the same. (This will explain the slight differences in the line numbers reported in my copy of the code and what's currently on github.)

I ran with the following command:

```
./bidmach grasp_scripts/testgrasp_daniel_forests.ssc | tee rf_iter_04.txt
```

The error message happens on the second pass:

```
99.00%, ll=-14.57985, gf=0.627, secs=178.4, GB=27.36, MB/s=153.41, GPUmem=0.951406
100.00%, ll=-14.76501, gf=0.628, secs=178.9, GB=27.49, MB/s=153.67, GPUmem=0.951406
purity gain 49.0682, fraction impure 1.000, nnew 4.0, nnodes 7.0
pass= 2
 1.00%, ll=-13.73432, gf=0.616, secs=183.3, GB=27.63, MB/s=150.80, GPUmem=0.951406
 2.00%, ll=-14.05489, gf=0.617, secs=183.9, GB=27.77, MB/s=151.00, GPUmem=0.951406
 3.00%, ll=-13.86559, gf=0.618, secs=184.6, GB=27.91, MB/s=151.17, GPUmem=0.951406
 4.00%, ll=-14.16203, gf=0.618, secs=185.6, GB=28.05, MB/s=151.15, GPUmem=0.951406
 5.00%, ll=-14.22883, gf=0.618, secs=186.3, GB=28.18, MB/s=151.29, GPUmem=0.951406
 6.00%, ll=-13.62708, gf=0.619, secs=187.0, GB=28.32, MB/s=151.46, GPUmem=0.951406
 7.00%, ll=-14.01970, gf=0.617, secs=188.4, GB=28.46, MB/s=151.05, GPUmem=0.951406
 8.00%, ll=-13.73041, gf=0.619, secs=189.0, GB=28.60, MB/s=151.34, GPUmem=0.951406
 9.00%, ll=-13.94019, gf=0.617, secs=190.2, GB=28.73, MB/s=151.06, GPUmem=0.951406
10.00%, ll=-13.94287, gf=0.617, secs=191.1, GB=28.87, MB/s=151.04, GPUmem=0.951406
11.00%, ll=-13.90285, gf=0.618, secs=191.7, GB=29.01, MB/s=151.31, GPUmem=0.951406
12.00%, ll=-14.19966, gf=0.619, secs=192.5, GB=29.15, MB/s=151.40, GPUmem=0.951406
13.00%, ll=-13.65219, gf=0.620, secs=193.1, GB=29.29, MB/s=151.66, GPUmem=0.951406
14.00%, ll=-14.01491, gf=0.616, secs=195.2, GB=29.42, MB/s=150.72, GPUmem=0.951406
15.00%, ll=-14.16214, gf=0.617, secs=195.8, GB=29.56, MB/s=150.95, GPUmem=0.951406
16.00%, ll=-14.29476, gf=0.617, secs=196.6, GB=29.69, MB/s=151.06, GPUmem=0.951406
17.00%, ll=-14.12481, gf=0.617, secs=197.5, GB=29.83, MB/s=151.04, GPUmem=0.951406
18.00%, ll=-13.96619, gf=0.618, secs=198.3, GB=29.97, MB/s=151.16, GPUmem=0.951406
19.00%, ll=-14.08349, gf=0.618, secs=199.0, GB=30.11, MB/s=151.28, GPUmem=0.951406
20.00%, ll=-13.82123, gf=0.617, secs=200.3, GB=30.24, MB/s=150.98, GPUmem=0.951406
21.00%, ll=-13.96104, gf=0.618, secs=200.9, GB=30.38, MB/s=151.25, GPUmem=0.951406
22.00%, ll=-13.52953, gf=0.617, secs=202.2, GB=30.52, MB/s=150.92, GPUmem=0.951406
23.00%, ll=-13.58494, gf=0.617, secs=203.3, GB=30.66, MB/s=150.83, GPUmem=0.951406
24.00%, ll=-14.42605, gf=0.618, secs=203.8, GB=30.80, MB/s=151.10, GPUmem=0.951406
25.00%, ll=-13.67770, gf=0.618, secs=204.7, GB=30.93, MB/s=151.13, GPUmem=0.951406
26.00%, ll=-14.07872, gf=0.619, secs=205.2, GB=31.07, MB/s=151.39, GPUmem=0.951406
27.00%, ll=-13.95486, gf=0.615, secs=207.4, GB=31.21, MB/s=150.48, GPUmem=0.951406
28.00%, ll=-14.05688, gf=0.616, secs=208.0, GB=31.35, MB/s=150.69, GPUmem=0.951406
29.00%, ll=-13.93663, gf=0.617, secs=208.7, GB=31.48, MB/s=150.81, GPUmem=0.951406
30.00%, ll=-14.02459, gf=0.616, secs=209.7, GB=31.62, MB/s=150.80, GPUmem=0.951406
31.00%, ll=-13.84258, gf=0.618, secs=210.2, GB=31.75, MB/s=151.06, GPUmem=0.951406
32.00%, ll=-13.96289, gf=0.618, secs=211.1, GB=31.90, MB/s=151.08, GPUmem=0.951406
33.00%, ll=-13.64708, gf=0.617, secs=212.4, GB=32.04, MB/s=150.84, GPUmem=0.951406
34.00%, ll=-13.83610, gf=0.618, secs=212.9, GB=32.17, MB/s=151.09, GPUmem=0.951406
35.00%, ll=-13.94848, gf=0.617, secs=214.2, GB=32.31, MB/s=150.81, GPUmem=0.951406
36.00%, ll=-13.80724, gf=0.616, secs=215.3, GB=32.44, MB/s=150.71, GPUmem=0.951406
37.00%, ll=-13.91969, gf=0.617, secs=215.8, GB=32.58, MB/s=150.96, GPUmem=0.951406
38.00%, ll=-13.62510, gf=0.617, secs=216.7, GB=32.72, MB/s=151.00, GPUmem=0.951406
39.00%, ll=-13.81619, gf=0.618, secs=217.2, GB=32.86, MB/s=151.28, GPUmem=0.951406
40.00%, ll=-13.85715, gf=0.616, secs=219.0, GB=32.99, MB/s=150.67, GPUmem=0.951406
41.00%, ll=-14.25707, gf=0.617, secs=219.7, GB=33.13, MB/s=150.82, GPUmem=0.951406
42.00%, ll=-13.37528, gf=0.617, secs=220.4, GB=33.27, MB/s=150.91, GPUmem=0.951406
43.00%, ll=-13.73678, gf=0.617, secs=221.5, GB=33.41, MB/s=150.85, GPUmem=0.951406
44.00%, ll=-13.63394, gf=0.618, secs=222.0, GB=33.55, MB/s=151.11, GPUmem=0.951406
45.00%, ll=-13.70074, gf=0.618, secs=222.9, GB=33.68, MB/s=151.11, GPUmem=0.951406
46.00%, ll=-14.13872, gf=0.617, secs=224.2, GB=33.82, MB/s=150.86, GPUmem=0.951406
47.00%, ll=-13.35995, gf=0.618, secs=224.7, GB=33.96, MB/s=151.09, GPUmem=0.951406
48.00%, ll=-13.62401, gf=0.616, secs=226.1, GB=34.10, MB/s=150.77, GPUmem=0.951406
49.00%, ll=-14.25777, gf=0.616, secs=227.2, GB=34.23, MB/s=150.67, GPUmem=0.951406
50.00%, ll=-13.54259, gf=0.617, secs=227.7, GB=34.37, MB/s=150.94, GPUmem=0.951406
51.00%, ll=-13.57308, gf=0.618, secs=228.4, GB=34.50, MB/s=151.05, GPUmem=0.951406
52.00%, ll=-13.91093, gf=0.619, secs=229.0, GB=34.65, MB/s=151.29, GPUmem=0.951406
count=2210707, inds3.length=2210707, counts3.length=2210707, counts1.length=2207004
java.lang.ArrayIndexOutOfBoundsException: 2210707
  at BIDMach.models.SVec.add(RandomForest.scala:1268)
  at BIDMach.models.SVTree.addSVec(RandomForest.scala:1317)
  at BIDMach.models.RandomForest$$anonfun$addSVecs$1.apply$mcVI$sp(RandomForest.scala:1195)
  at BIDMach.models.RandomForest$$anonfun$addSVecs$1.apply(RandomForest.scala:1195)
  at BIDMach.models.RandomForest$$anonfun$addSVecs$1.apply(RandomForest.scala:1195)
  at scala.collection.parallel.immutable.ParRange$ParRangeIterator.map2combiner(ParRange.scala:105)
  at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1053)
  at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
  at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
  at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
  at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
  at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1050)
  at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:159)
  at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
  at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
  at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
  at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

This corresponds to line 1253 in the Random Forest code (which is line 1268 in my code), with count being 2210707 and the inds3 having length exactly that, so the error is "one off".

I have attached the output log file as it's pretty long. The output log file also contains the ```opts.what``` value so you can see the exact settings I chose in the Random Forest learner.

[rf_iter_04.txt](https://github.com/BIDData/BIDMach/files/172349/rf_iter_04.txt)

The strange thing is, I had previously run this code exactly the same as before, with one exception (I set npasses = 5, not npasses = 4), and the code worked and ran through all 5 passes. I will re-run this same code with npasses = 4 again to see if the error happens in the same location.

Thanks,
Daniel

**Comment by DanielTakeshi** [comment]
I re-ran the exact same command:

```
./bidmach grasp_scripts/testgrasp_daniel_forests.ssc | tee rf_iter_04.txt
```

And this time, the code worked without errors. It went through all 4 iterations normally. So indeed, this is nondeterministic.

**Comment by jcanny** [comment]
Hi Daniel,
This error is happening in a piece of parallel code (using Scala parallel collections). Its important to report all the system information - what OS you're running and especially what java version. Its happening in a fairly simple piece of code that is making only local changes within a fork/join section, which suggests that it may be a problem in the parallel collection implementation.  I've never seen this error in spite of running forests for many hours on large datasets, so its also likely to be configuration-dependent.

**Comment by jcanny** [comment]
PS, you can probably make it go away by removing the ".par" method in 

  def addSVecs(a:Array[SVec], totals:Array[SVTree]) { 
    (0 until ntrees).par.map(i => {totals(i).addSVec(a(i));});
  }
around line 1194 in RandomForest.scala.

**Comment by DanielTakeshi** [comment]
I'm running on the 'bitter' machine. Regarding the Java version:

```
seita@bitter:~/BIDMach$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

OK, i will try and remove the '.par' stuff and try again. I'll report back after a few test runs

**Comment by DanielTakeshi** [comment]
I ran this code again with the fix you mentioned (deleting those four characters) and it seems to be OK. The code above works, and I tried with 10 iterations and the code still works. The downside, of course, is that the gflops is now halved, but it's tough to think of a better alternative. Thanks John.

**Comment by DanielTakeshi** [comment]
Sorry, I spoke too soon. I ran a third time and got the same error. Huh ... perhaps I should be removing more 'par's in the code.

```
98.00%, ll=-13.10656, gf=0.232, secs=1209.4, GB=68.46, MB/s=56.61, GPUmem=0.916003
99.00%, ll=-12.39616, gf=0.232, secs=1211.1, GB=68.60, MB/s=56.65, GPUmem=0.916003
100.00%, ll=-12.51205, gf=0.232, secs=1212.9, GB=68.73, MB/s=56.67, GPUmem=0.916003
purity gain 18.2374, fraction impure 1.000, nnew 32.0, nnodes 63.0
pass= 5
 1.00%, ll=-12.27485, gf=0.231, secs=1221.4, GB=68.87, MB/s=56.39, GPUmem=0.916003
 2.00%, ll=-12.55434, gf=0.231, secs=1223.4, GB=69.01, MB/s=56.41, GPUmem=0.916003
 3.00%, ll=-12.27102, gf=0.231, secs=1224.9, GB=69.15, MB/s=56.45, GPUmem=0.916003
 4.00%, ll=-12.64663, gf=0.231, secs=1227.9, GB=69.29, MB/s=56.43, GPUmem=0.916003
 5.00%, ll=-12.66354, gf=0.231, secs=1230.1, GB=69.42, MB/s=56.43, GPUmem=0.916003
 6.00%, ll=-12.20014, gf=0.231, secs=1231.8, GB=69.56, MB/s=56.47, GPUmem=0.916003
 7.00%, ll=-12.53224, gf=0.231, secs=1236.6, GB=69.70, MB/s=56.36, GPUmem=0.916003
 8.00%, ll=-12.18264, gf=0.231, secs=1238.2, GB=69.84, MB/s=56.40, GPUmem=0.916003
 9.00%, ll=-12.51731, gf=0.231, secs=1240.6, GB=69.97, MB/s=56.40, GPUmem=0.916003
10.00%, ll=-12.40475, gf=0.231, secs=1243.9, GB=70.11, MB/s=56.36, GPUmem=0.916003
11.00%, ll=-12.54472, gf=0.231, secs=1246.2, GB=70.25, MB/s=56.37, GPUmem=0.916003
12.00%, ll=-12.74647, gf=0.231, secs=1248.1, GB=70.39, MB/s=56.39, GPUmem=0.916003
13.00%, ll=-12.18430, gf=0.231, secs=1249.6, GB=70.53, MB/s=56.44, GPUmem=0.916003
14.00%, ll=-12.43180, gf=0.230, secs=1256.1, GB=70.66, MB/s=56.25, GPUmem=0.916003
15.00%, ll=-12.55587, gf=0.230, secs=1258.1, GB=70.80, MB/s=56.28, GPUmem=0.916003
16.00%, ll=-12.75135, gf=0.231, secs=1259.7, GB=70.93, MB/s=56.31, GPUmem=0.916003
17.00%, ll=-12.48337, gf=0.231, secs=1262.6, GB=71.07, MB/s=56.29, GPUmem=0.916003
18.00%, ll=-12.51669, gf=0.230, secs=1265.1, GB=71.21, MB/s=56.29, GPUmem=0.916003
19.00%, ll=-12.67011, gf=0.231, secs=1266.6, GB=71.35, MB/s=56.33, GPUmem=0.916003
inds3.length=2575413, count=2575413
java.lang.ArrayIndexOutOfBoundsException: 2575413
  at BIDMach.models.SVec.add(RandomForest.scala:1249)
  at BIDMach.models.SVTree.addSVec(RandomForest.scala:1318)
  at BIDMach.models.RandomForest$$anonfun$addSVecs$1.apply$mcVI$sp(RandomForest.scala:1196)
  at BIDMach.models.RandomForest$$anonfun$addSVecs$1.apply(RandomForest.scala:1196)
  at BIDMach.models.RandomForest$$anonfun$addSVecs$1.apply(RandomForest.scala:1196)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.immutable.Range.foreach(Range.scala:160)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at BIDMach.models.RandomForest.addSVecs(RandomForest.scala:1196)
  at BIDMach.models.RandomForest.dobatch(RandomForest.scala:319)
  at BIDMach.models.Model.dobatchg(Model.scala:175)
  at BIDMach.Learner.nextPass(Learner.scala:135)
  at BIDMach.Learner.retrain(Learner.scala:82)
  at BIDMach.Learner.train(Learner.scala:69)
  ... 138 elided
```

**Comment by mattmacy** [comment]
It sounds like a synchronization bug in the jdk itself - e.g. an unserialized update to the array index. Have you tried openjdk8?

**Comment by DanielTakeshi** [comment]
I have not tried openjdk8. I will investigate how to do that.

**Comment by jcanny** [comment]
Daniel,
Can you show me the source code where the error is happening? Since 
you've added some lines, I cant get that from the stack dump.


-John

**Comment by jcanny** [comment]
I switched to Oracle Java 7 and ran the same example and hit memory limit errors on the same machine/dataset. its likely this problem is caused by GC activity while the machine is thrashing with too little memory. This problem has never occurred on a normally-loaded machine, so I'm going to close out the issue.
