### ISSUE TITLE
could not initialize class edu.berkeley.bid.CBLAS

### ISSUE THREAD

**Issue by xinleipan** [BIDData/BIDMach#123]
I'm trying to use the function "^*" but got the error "could not initialize class edu.berkeley.bid.CBLAS". Is "^*" a built-in matrix operation in the latest release of BIDMach?

**Comment by xinleipan** [comment]
Sorry the function is "^*". The previous issue contains a typo but the problem exists.

**Comment by jcanny** [comment]
Its a configuration error. Please explain exactly how you are running 
BIDMach.

-John

**Comment by xinleipan** [comment]
So the code goes like this ...

Xinleis-MacBook-Pro:git xinleipan$ cd BIDMach
Xinleis-MacBook-Pro:BIDMach xinleipan$ ./bidmach
Loading /Users/xinleipan/git/BIDMach/lib/bidmach_init.scala...
import BIDMat.{CMat, CSMat, DMat, Dict, FMat, FND, GMat, GDMat, GIMat, GLMat, GSMat, GSDMat, HMat, IDict, Image, IMat, LMat, Mat, SMat, SBMat, SDMat}
import BIDMat.MatFunctions._
import BIDMat.SciFunctions._
import BIDMat.Solvers._
import BIDMat.Plotting._
import BIDMach.Learner
import BIDMach.models.{FM, GLM, KMeans, KMeansw, LDA, LDAgibbs, Model, NMF, SFA, RandomForest}
import BIDMach.networks.DNN
import BIDMach.datasources.{DataSource, MatDS, FilesDS, SFilesDS}
import BIDMach.mixins.{CosineSim, Perplexity, Top, L1Regularizer, L2Regularizer}
import BIDMach.updaters.{ADAGrad, Batch, BatchNorm, IncMult, IncNorm, Telescoping}
import BIDMach.causal.IPTW
Cant find native CPU libraries
Cant find native HDF5 library
Couldnt load CUDA runtime

Welcome to Scala version 2.11.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_65).
Type in expressions to have them evaluated.
Type :help for more information.

scala> val a = dones(3,3)
a: BIDMat.DMat =
   1   1   1
   1   1   1
   1   1   1

scala> val b = dones(3,3)
b: BIDMat.DMat =
   1   1   1
   1   1   1
   1   1   1

scala> val c = a ^* b
java.lang.UnsatisfiedLinkError: Could not load the native library.
Error while loading native library "bidmatmkl-apple-x86_64" with base name "bidmatmkl"
Operating system name: Mac OS X
Architecture         : x86_64
Architecture bit size: 64
Stack trace from the attempt to load the library as a resource:
java.lang.NullPointerException: No resource found with name '/lib/libbidmatmkl-apple-x86_64.jnilib'
	at jcuda.LibUtils.loadLibraryResource(LibUtils.java:149)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:83)
	at edu.berkeley.bid.CBLAS.<clinit>(CBLAS.java:8)
	at BIDMat.DMat.Tmult(DMat.scala:444)
	at BIDMat.DMat.$up$times(DMat.scala:729)
	at .<init>(<console>:29)
	at .<clinit>(<console>)
	at .$print$lzycompute(<console>:7)
	at .$print(<console>:6)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:739)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:986)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:593)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:592)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:592)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:524)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:520)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:754)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:799)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:666)
	at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:433)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:450)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:868)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:854)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:854)
	at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:95)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:854)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: no bidmatmkl-apple-x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:94)
	at edu.berkeley.bid.CBLAS.<clinit>(CBLAS.java:8)
	at BIDMat.DMat.Tmult(DMat.scala:444)
	at BIDMat.DMat.$up$times(DMat.scala:729)
	at .<init>(<console>:29)
	at .<clinit>(<console>)
	at .$print$lzycompute(<console>:7)
	at .$print(<console>:6)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:739)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:986)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:593)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:592)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:592)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:524)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:520)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:754)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:799)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:666)
	at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:433)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:450)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:868)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:854)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:854)
	at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:95)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:854)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

  at jcuda.LibUtils.loadLibrary(LibUtils.java:126)
  at edu.berkeley.bid.CBLAS.<clinit>(CBLAS.java:8)
  at BIDMat.DMat.Tmult(DMat.scala:444)
  at BIDMat.DMat.$up$times(DMat.scala:729)
  ... 33 elided

scala> val c = a^*b
java.lang.NoClassDefFoundError: Could not initialize class edu.berkeley.bid.CBLAS
  at BIDMat.DMat.Tmult(DMat.scala:444)
  at BIDMat.DMat.$up$times(DMat.scala:729)
  ... 33 elided

**Comment by byeah** [comment]
what's the details about this error? you can attach the entire error
message which will track the code base

**Comment by byeah** [comment]
oh, i see . your native library is not loading correctly. did you use
./getdevlibs.sh to get the libraries?

**Comment by xinleipan** [comment]
@byeah Thank you! It works using "./getdevlibs.sh". However, since I didn't clone BIDMach from the repo but downloaded the latest release which does not contain this script. So it's better to get BIDMach by cloning from the git repo.

**Comment by jcanny** [comment]
Yes, I've updated the installation instuctions.

-John
