### ISSUE TITLE
loadSMat expected type field 231 or 331 but was 130

### ISSUE THREAD

**Issue by manvendratomar** [BIDData/BIDMach#129]
When trying to run tutorial for MNIST8 with LDA it breaks with above runtime exception
java.lang.RuntimeException: loadSMat expected type field 231 or 331 but was 130
  at BIDMat.HMat$.loadSMat(HMat.scala:917)
  at BIDMat.HMat$.loadSMat(HMat.scala:902)
  at BIDMat.MatFunctions$.loadSMat(MatFunctions.scala:2027)
  at BIDMach.datasources.SFileSource$$anonfun$init$1.apply(SFileSource.scala:197)
  at BIDMach.datasources.SFileSource$$anonfun$init$1.apply(SFileSource.scala:196)
  at scala.collection.immutable.Range.foreach(Range.scala:160)
  at BIDMach.datasources.SFileSource.init(SFileSource.scala:196)
  at BIDMach.Learner.init(Learner.scala:56)
  at BIDMach.Learner.firstPass(Learner.scala:93)
  at BIDMach.Learner.retrain(Learner.scala:82)
  at BIDMach.Learner.train(Learner.scala:71)

**Comment by GearFear** [comment]
Try to use loadFMat instead
