### ISSUE TITLE
testsmf.ssc Runtime Error

### ISSUE THREAD

**Issue by xlxie** [BIDData/BIDMach#158]
Hi,

I am trying to run BIDMach on my TitanX GPU for matrix factorization. When I try to run testsmf.ssc, runtime error occurs:

...
lambda: Float = 4.0
opts.lambdau: Float = 4.0
opts.regumean: Float = 4.0
opts.lambdam: Float = 1.6E-4
opts.regmmean: Float = 1.6E-4
opts.evalStep: Int = 31
opts.doUsers: Boolean = false
opts.lsgd: Float = 0.01
pass= 0
java.lang.NullPointerException
  at scala.collection.mutable.ArrayOps$ofInt$.length$extension(ArrayOps.scala:240)
  at scala.collection.mutable.ArrayOps$ofInt.length(ArrayOps.scala:240)
  at scala.collection.IndexedSeqOptimized$class.reduceLeft(IndexedSeqOptimized.scala:74)
  at scala.collection.mutable.ArrayOps$ofInt.reduceLeft(ArrayOps.scala:234)
  at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:193)
  at scala.collection.mutable.ArrayOps$ofInt.reduce(ArrayOps.scala:234)
  at BIDMat.GMat$.make(GMat.scala:2060)
  at BIDMat.GMat$.newOrCheckGMat(GMat.scala:2198)
  at BIDMat.GMat$.newOrCheckGMat(GMat.scala:2271)
  at BIDMat.GMat$.newOrCheckGMat(GMat.scala:2278)
  at BIDMat.GMat.dot(GMat.scala:958)
  at BIDMat.GMat.dot(GMat.scala:20)
  at BIDMat.FPair.dot(FMat.scala:2214)
  at BIDMat.Mop_Dot$.op(Operators.scala:321)
  at BIDMat.Mop$class.op(Operators.scala:41)
  at BIDMat.Mop_Dot$.op(Operators.scala:319)
  at BIDMat.GMat.dot(GMat.scala:1653)
  at BIDMach.models.SMF.accept(SMF.scala:222)
  at BIDMach.models.SMF$$anonfun$uupdate$1.apply$mcVI$sp(SMF.scala:153)
  at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
  at BIDMach.models.SMF.uupdate(SMF.scala:147)
  at BIDMach.models.FactorModel.dobatch(FactorModel.scala:55)
  at BIDMach.models.Model.dobatchg(Model.scala:201)
  at BIDMach.Learner.nextPass(Learner.scala:145)
  at BIDMach.Learner.firstPass(Learner.scala:114)
  at BIDMach.Learner.retrain(Learner.scala:88)
  at BIDMach.Learner.train(Learner.scala:75)
  ... 54 elided
...

It seems that the error occurs when testsmf.ssc calls "nn.train". 

I have same problem on another machine with P100 GPU. 

Some background info:
        Install: I checked out the latest version and used "mvn package" to install. A warning "[WARNING] Multiple versions of scala libraries detected!" occurred during the installation.
        Toolkit: Opensuse 13.2, cuda 8.0

Does anyone have any idea?

**Comment by xlxie** [comment]
I installed BIDMach 1.1.2 and now it works.

It seems that the beta version is not as robust as the release version.
