### ISSUE TITLE
Error in running LDA scripts

### ISSUE THREAD

**Issue by zenzang** [BIDData/BIDMach#164]
I'm relative new to BIDMach. So I'm trying to LDA in uci pubmed dataset. I have downloaded the dataset and run `processpubmed.ssc` successfully. But when I run `pubmedlda.ssc`, I got the following error. Could someone help me solve this problem please?
```
Loading pubmedlda.ssc...
dir: String = ../data/uci/
nn: BIDMach.Learner = Learner(BIDMach.datasources.SFileSource@6ff415ad,BIDMach.models.LDA@280d9edc,null,BIDMach.updaters.IncNorm@28fd3dc1,null,BIDMach.models.LDA$FileOpts@5f9b6ae7)
opts: BIDMach.models.LDA.FileOpts = BIDMach.models.LDA$FileOpts@5f9b6ae7
opts.nend: Int = 9
opts.eltsPerSample: Int = 400
opts.batchSize: Int = 20000
opts.npasses: Int = 3
dict: BIDMat.Dict = BIDMat.Dict@5d97caa4
java.lang.RuntimeException: SFileSource index out of range. Try increasing opts.eltsPerSample
  at BIDMach.datasources.SFileSource.spcolslice(SFileSource.scala:80)
  at BIDMach.datasources.SFileSource.next(SFileSource.scala:160)
  at BIDMach.models.Model.bind(Model.scala:181)
  at BIDMach.Learner.init(Learner.scala:71)
  at BIDMach.Learner.firstPass(Learner.scala:141)
  at BIDMach.Learner.retrain(Learner.scala:128)
  at BIDMach.Learner.train(Learner.scala:115)
  ... 54 elided

```

**Comment by byeah** [comment]
According to the error message, one straightforward solution is to try to set opts.eltsPerSample to be something larger, say 1000.

**Comment by jcanny** [comment]
There was a datasource error which should be fixed now. Try pulling from master, doing mvn clean install and doing it again.
