### ISSUE TITLE
getnativepath issues

### ISSUE THREAD

**Issue by coryschillaci** [BIDData/BIDMach#34]
Running `./bidmach notebook` from the latest distribution, the terminal output is:
>Error: Could not find or load main class getnativepath
2015-02-25 15:06:18.968 [NotebookApp] Using existing profile dir: u'/Users/coryschillaci/.ipython/profile_scala'
2015-02-25 15:06:18.978 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
2015-02-25 15:06:19.008 [NotebookApp] Serving notebooks from local directory: /Users/coryschillaci/Desktop/StressProject/BIDMach_1.0.0-osx-x86_64
2015-02-25 15:06:19.008 [NotebookApp] 0 active kernels 
2015-02-25 15:06:19.008 [NotebookApp] The IPython Notebook is running at: http://localhost:8888/
2015-02-25 15:06:19.008 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
^C2015-02-25 15:06:42.219 [NotebookApp] interrupted
Serving notebooks from local directory: /Users/coryschillaci/Desktop/StressProject/BIDMach_1.0.0-osx-x86_64
0 active kernels 
The IPython Notebook is running at: http://localhost:8888/ 

When I run the `BIDMach_intro.pynb` tutorial, the first cell output is 
> Cant find native CPU libraries  
> Cant find native HDF5 library  
> Couldnt load CUDA runtime  
> Out[1]:  
> ()

The first error occurs when I run the section called "Transposed Multiplies," the first input gives
>java.lang.UnsatisfiedLinkError: Could not load the native library.
Error while loading native library "bidmatmkl-apple-x86_64" with base name "bidmatmkl"
Operating system name: Mac OS X
Architecture         : x86_64
Architecture bit size: 64
Stack trace from the attempt to load the library as a resource:
java.lang.NullPointerException: No resource found with name '/lib/libbidmatmkl-apple-x86_64.jnilib'
	at jcuda.LibUtils.loadLibraryResource(LibUtils.java:149)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:83)
	at edu.berkeley.bid.CBLAS.<clinit>(CBLAS.java:8)
	at BIDMat.FMat.Tmult(FMat.scala:565)
	at BIDMat.FPair.Tx(FMat.scala:1113)
	at BIDMat.Mop_TTimes$.op(Operators.scala:370)
	at BIDMat.Mop$class.op(Operators.scala:37)
	at BIDMat.Mop_TTimes$.op(Operators.scala:368)
	at BIDMat.FMat.$up$times(FMat.scala:888)
	at .<init>(<console>:48)
	at .<clinit>(<console>)
	at .$result$lzycompute(<console>:5)
	at .$result(<console>:5)
	at $result(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:739)
	at org.refptr.iscala.Interpreter$$anonfun$9.apply(Interpreter.scala:206)
	at org.refptr.iscala.Interpreter.withException(Interpreter.scala:101)
	at org.refptr.iscala.Interpreter.loadAndRunReq(Interpreter.scala:206)
	at org.refptr.iscala.Interpreter$$anonfun$interpret$1.apply(Interpreter.scala:245)
	at org.refptr.iscala.Interpreter$$anonfun$interpret$1.apply(Interpreter.scala:245)
	at org.refptr.iscala.Runner$Execution$$anonfun$1.apply$mcV$sp(Runner.scala:28)
	at org.refptr.iscala.IOUtil$$anon$2.run(Util.scala:21)
	at java.lang.Thread.run(Thread.java:745)
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: no bidmatmkl-apple-x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:94)
	at edu.berkeley.bid.CBLAS.<clinit>(CBLAS.java:8)
	at BIDMat.FMat.Tmult(FMat.scala:565)
	at BIDMat.FPair.Tx(FMat.scala:1113)
	at BIDMat.Mop_TTimes$.op(Operators.scala:370)
	at BIDMat.Mop$class.op(Operators.scala:37)
	at BIDMat.Mop_TTimes$.op(Operators.scala:368)
	at BIDMat.FMat.$up$times(FMat.scala:888)
	at .<init>(<console>:48)
	at .<clinit>(<console>)
	at .$result$lzycompute(<console>:5)
	at .$result(<console>:5)
	at $result(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:739)
	at org.refptr.iscala.Interpreter$$anonfun$9.apply(Interpreter.scala:206)
	at org.refptr.iscala.Interpreter.withException(Interpreter.scala:101)
	at org.refptr.iscala.Interpreter.loadAndRunReq(Interpreter.scala:206)
	at org.refptr.iscala.Interpreter$$anonfun$interpret$1.apply(Interpreter.scala:245)
	at org.refptr.iscala.Interpreter$$anonfun$interpret$1.apply(Interpreter.scala:245)
	at org.refptr.iscala.Runner$Execution$$anonfun$1.apply$mcV$sp(Runner.scala:28)
	at org.refptr.iscala.IOUtil$$anon$2.run(Util.scala:21)
	at java.lang.Thread.run(Thread.java:745)

>    jcuda.LibUtils.loadLibrary(LibUtils.java:126)
    edu.berkeley.bid.CBLAS.<clinit>(CBLAS.java:8)
    BIDMat.FMat.Tmult(FMat.scala:565)
    BIDMat.FPair.Tx(FMat.scala:1113)
    BIDMat.Mop_TTimes$.op(Operators.scala:370)
    BIDMat.Mop$class.op(Operators.scala:37)
    BIDMat.Mop_TTimes$.op(Operators.scala:368)
    BIDMat.FMat.$up$times(FMat.scala:888)

**Comment by jcanny** [comment]
Achh, sorry. The getnativepath routine was checked into github but had to be manually added to the bundling scripts. Its there now for all versions.

**Comment by coryschillaci** [comment]
Works with the update
