### ISSUE TITLE
BIDMach needs an updated BIDMat.jar

### ISSUE THREAD

**Issue by DanielTakeshi** [BIDData/BIDMach#35]
I'm using Mac OS X 10.9.5 and have run into the same problems I outlined in https://github.com/BIDData/BIDMat/issues/18. Here's an example of a problem for quick reference:

scala> val diag = BIDMat.GMat(1 on 2 on 3)
diag: BIDMat.GMat =
   1
   2
   3

scala> mkdiag(diag)
java.lang.RuntimeException: mkdiag requires a vector argument, but dims= 3 1
  at BIDMat.GMat.mkdiag(GMat.scala:643)
  at BIDMat.MatFunctions$.mkdiag(MatFunctions.scala:1442)
  ... 33 elided

scala> 

The issue is that while I've added some fixes to BIDMat that resolve the above problem (plus others), they are not reflected in the latest BIDMat.jar that ships with BIDMach. The problem above happens when I downloaded the fresh 1.0.0 Mac bundle and typed in ./bidmach and then the commands above. Thus, the solution is simply to recompile BIDMat to get BIDMat.jar, and then copy that over to BIDMach's "lib" file in the 1.0.0 bundle, and that should fix things.

Also, the BIDMat API docs need to be updated since they do not have recent fixes and updated documentation.

**Comment by DanielTakeshi** [comment]
Closed this, as it's been fixed.
