### ISSUE TITLE
DNN.learner methods don't work

### ISSUE THREAD

**Issue by coryschillaci** [BIDData/BIDMach#52]
When trying to create a dnn with `DNN.learner`, the ADAGrad initialization step from `Learner.init` gives the error
```
java.lang.NullPointerException
  at BIDMach.updaters.ADAGrad$$anonfun$init$1.apply$mcVI$sp(ADAGrad.scala:34)
  at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
  at BIDMach.updaters.ADAGrad.init(ADAGrad.scala:33)
  at BIDMach.Learner.init(Learner.scala:45)
```
This seems to be due to DNN waiting to initialize the modelmats until the first call to forward. 

It looks like the correct way to set a DNN to use ADAGrad is to set `aopts` rather than adding an updater to the learner, is this correct?

**Comment by jcanny** [comment]
SHould work either way now.
