### ISSUE TITLE
colslice index out of range in RF learner

### ISSUE THREAD

**Issue by atitov-git** [BIDData/BIDMach#59]
I am trying to get the precompiled **BIDMach_1.0.3-linux-86_64/bidmach** to work with RF binary classification on a sample dataset, but getting an error:

```scala
scala> val trg  = loadIMat("../../RF_project/gisette/gisette_train.data.txt")
trg: BIDMat.IMat =
  550    0  495    0    0    0    0  976    0    0    0    0  983    0  995    0  983    0    0  983    0    0    0    0...
    0    0    0    0    0    0    0  976    0    0    0    0    0    0  584    0    0    0    0    0    0    0    0    0...
    0    0    0    0    0    0    0    0    0    0    0    0  983    0  995  983  976    0    0    0    0    0    0    0...
    0    0  742    0    0    0    0  684    0  956    0    0  983    0  991  816  983    0    0    0    0    0    0    0...
    0    0    0    0    0    0    0  608    0  979    0    0    0    0  972    0    0    0    0    0    0    0    0  480...
   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..

scala> val (nn,mopts) =RandomForest.learner(trg,yg)
nn: BIDMach.Learner = Learner(BIDMach.datasources.MatDS@61d91a71,BIDMach.models.RandomForest@745722e6,null,BIDMach.updaters.Batch@4b465b6,BIDMach.models.RandomForest$RFSopts@5f819223)
mopts: BIDMach.models.RandomForest.RFSopts = BIDMach.models.RandomForest$RFSopts@5f819223

scala> nn.train
java.lang.RuntimeException: colslice index out of range 5000 1
  at BIDMat.DenseMat$mcI$sp.gcolslice$mcI$sp(DenseMat.scala:469)
  at BIDMat.IMat.colslice(IMat.scala:99)
  at BIDMat.IMat.colslice(IMat.scala:7)
  at BIDMach.datasources.MatDS$$anonfun$next$1.apply$mcVI$sp(MatDS.scala:43)
  at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
  at BIDMach.datasources.MatDS.next(MatDS.scala:41)
  at BIDMach.models.Model.bind(Model.scala:81)
  at BIDMach.Learner.init(Learner.scala:42)
  at BIDMach.Learner.train(Learner.scala:52)
  ... 33 elided
```
Train dataset is space separated integer data from UCI (gisette dataset). I can't believe that column slicing does not work for RF in BIDMach, so I must be doing something obviously wrong. Notably RF.learner does not take the same data in floating point, even though the BIDMach API doc says that discrete (integer) values are only needed for regression testing. 

Any advice?

**Comment by jcanny** [comment]
If you're using data directly from UCI, then its probably in row major-order. BIDMach uses column-major order, like Matlab and Fortran, and so the columns of a dataset correspond to feature instances. You probably need to transpose both input matrices before using them.
