### ISSUE TITLE
workout.ssc script runs out of heap memory on fairly powerful Linux Box

### ISSUE THREAD

**Issue by kjameslubin** [BIDData/BIDMach#64]
```
<<<<<<< Testing FM on RCV1 (2 passes) >>>>>>>
corpus perplexity=20457.245630
pass= 0
```
leads to
```
corpus perplexity=5879.116630
java.lang.OutOfMemoryError: Java heap space
  at BIDMat.FMat$.apply(FMat.scala:1578)
  at BIDMat.FMat$.zeros(FMat.scala:1609)
  at BIDMat.FMat.zeros(FMat.scala:290)
  at BIDMat.FMat.zeros(FMat.scala:14)
  at BIDMach.models.FM.init(FM.scala:115)
  at BIDMach.Learner.predict(Learner.scala:134)
  ... 26 elided
```

**Comment by jcanny** [comment]
Please provide a bit more information. How much memory does the machine have? How are you running BIDMach? i.e. how much memory is it being given?

**Comment by kjameslubin** [comment]
We discussed this in person - it's probably not such a big deal. My machine has 32 GB of RAM and I ran on default settings ... I can try to manually override the JVM heapsize if you would like me to try to reproduce it. In person we concluded that the issue would likely be fixed by turning caching off for the CPU portion of the execution. The GPU part went through without issue.

**Comment by kjameslubin** [comment]
So, the out of memory issue is eliminated by commenting the GPU part from workout.ssc. There are some odd errors in the CPU part - perhaps I've caused them with local changes. They all look like:
```
<<<<<<< Testing NMF on NYTimes (2 passes) >>>>>>>
corpus perplexity=11327.312875
pass= 0
java.lang.RuntimeException: xT dimensions mismatch (128 5000) (5000 102660)
  at BIDMat.FMat.multT(FMat.scala:693)
  at BIDMat.FPair.$times$up(FMat.scala:1671)

```
I can confirm that un-commenting the GPU code leads to the same out of memory error, and the dimension mismatch errors persist in that setting (as we'd expect - they are in the CPU section).
