### ISSUE TITLE
Error Trace

### ISSUE THREAD

**Issue by kjameslubin** [BIDData/BIDMach#66]
Following our conversation, the colslice is not in GLM. It's in [MatDS.scala](https://github.com/BIDData/BIDMach/blob/master/src/main/scala/BIDMach/datasources/MatDS.scala#L38-L51). I still think it's worth implementing, but I'm open to a workaround. 

```
java.lang.RuntimeException: operator colslice not implemented for TMat
  at BIDMat.Mat.notImplemented0(Mat.scala:23)
  at BIDMat.Mat.colslice(Mat.scala:80)
  at BIDMach.datasources.MatDS$$anonfun$next$1.apply$mcVI$sp(MatDS.scala:43)
  at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
  at BIDMach.datasources.MatDS.next(MatDS.scala:41)
  at BIDMach.models.Model.bind(Model.scala:81)
  at BIDMach.Learner.init(Learner.scala:42)
  at BIDMach.Learner.train(Learner.scala:52)
```

**Comment by kjameslubin** [comment]
I've got a version of colslice working. sum is the next operator of this nature to implement (or, really, a generalized reduce). I also think it's worth it, but just FYI
