### ISSUE TITLE
missing catname.imat

### ISSUE THREAD

**Issue by christopher5106** [BIDData/BIDMach#87]
Dears,

In command `./scripts/getrcv1.sh` in `./scripts/getdata.sh`, there is a failing command due to missing rcv1_fmt.txt file : 

```
cbin/tparse.exe -i rcv1-v2.topics.qrels.gz -f "data/rcv1/../rcv1_fmt.txt" -o "./" -m "./" -d " "
couldnt open format file
terminate called without an active exception
Abandon
```

This leads to further issues

```
Loading scripts/getrcv1.ssc...
defined object RCV1
Preprocessing
Making Sparse Data Matrix
Making Category Matrix
java.io.FileNotFoundException: data/rcv1/tokenized/../catname.imat (Aucun fichier ou dossier de ce type)
  at java.io.FileInputStream.open(Native Method)
  at java.io.FileInputStream.<init>(FileInputStream.java:146)
  at java.io.FileInputStream.<init>(FileInputStream.java:101)
  at BIDMat.HMat$.getInputStream(HMat.scala:156)
  at BIDMat.HMat$.loadIMat(HMat.scala:432)
  at BIDMat.HMat$.loadIMat(HMat.scala:454)
  at BIDMat.MatFunctions$.loadIMat(MatFunctions.scala:1976)
  at RCV1$.mkcats(<console>:87)
  at RCV1$.prepare(<console>:33)
  ... 54 elided

```

Where can I get the missing file ?
Thanks a lot

**Comment by jcanny** [comment]
Sorry, it was accidentally deleted. Its back there now.

**Comment by christopher5106** [comment]
Works well, thanks!
