### ISSUE TITLE
workout.ssc on GPU after 1 pass gives this error

### ISSUE THREAD

**Issue by manjunaths** [BIDData/BIDMach#89]
Hello,
I am trying to run the workout.ssc on a fairly powerful GPU box and I get this error with the mnist8m dataset. It doesn't run for 4 passes. Does anyone know what is happening ?

<<<<<<< Testing parallel KMeans with FilesDS on MNIST8M (4 passes) >>>>>>>
pass= 0
First pass random centroid initialization
First pass random centroid initialization
 3.00%, ll=0.00000, gf=56.074, secs=2.3, GB=0.76, MB/s=327.85, GPUmem=0.89, 0.97
 6.00%, ll=0.00000, gf=75.164, secs=3.5, GB=1.40, MB/s=402.84, GPUmem=0.89, 0.89
10.00%, ll=0.00000, gf=78.380, secs=5.0, GB=2.29, MB/s=458.26, GPUmem=0.89, 0.89
13.00%, ll=0.00000, gf=86.569, secs=6.0, GB=2.92, MB/s=485.05, GPUmem=0.89, 0.89
16.00%, ll=0.00000, gf=89.345, secs=7.3, GB=3.68, MB/s=504.96, GPUmem=0.89, 0.89
19.00%, ll=0.00000, gf=92.924, secs=8.4, GB=4.32, MB/s=513.11, GPUmem=0.89, 0.89
22.00%, ll=0.00000, gf=96.501, secs=9.5, GB=4.95, MB/s=523.90, GPUmem=0.89, 0.89
25.00%, ll=0.00000, gf=86.828, secs=12.0, GB=5.59, MB/s=465.35, GPUmem=0.89, 0.89
28.00%, ll=0.00000, gf=87.005, secs=13.5, GB=6.35, MB/s=471.01, GPUmem=0.89, 0.89
31.00%, ll=0.00000, gf=89.554, secs=14.6, GB=6.99, MB/s=479.96, GPUmem=0.89, 0.89
35.00%, ll=0.00000, gf=89.912, secs=15.9, GB=7.88, MB/s=493.82, GPUmem=0.89, 0.89
38.00%, ll=0.00000, gf=91.801, secs=17.0, GB=8.51, MB/s=499.45, GPUmem=0.89, 0.89
41.00%, ll=0.00000, gf=93.452, secs=18.1, GB=9.15, MB/s=504.35, GPUmem=0.89, 0.89
44.00%, ll=0.00000, gf=94.954, secs=19.2, GB=9.78, MB/s=508.90, GPUmem=0.89, 0.89
47.00%, ll=0.00000, gf=95.810, secs=20.4, GB=10.54, MB/s=516.60, GPUmem=0.89, 0.89
50.00%, ll=0.00000, gf=97.302, secs=21.4, GB=11.18, MB/s=521.48, GPUmem=0.89, 0.89
54.00%, ll=0.00000, gf=97.276, secs=22.8, GB=12.07, MB/s=529.71, GPUmem=0.89, 0.89
57.00%, ll=0.00000, gf=98.250, secs=23.9, GB=12.70, MB/s=531.88, GPUmem=0.89, 0.89
60.00%, ll=0.00000, gf=99.389, secs=24.9, GB=13.34, MB/s=535.22, GPUmem=0.89, 0.89
63.00%, ll=0.00000, gf=100.017, secs=26.1, GB=14.10, MB/s=540.91, GPUmem=0.89, 0.89
66.00%, ll=0.00000, gf=100.714, secs=27.2, GB=14.74, MB/s=542.11, GPUmem=0.89, 0.89
69.00%, ll=0.00000, gf=101.414, secs=28.3, GB=15.37, MB/s=543.52, GPUmem=0.89, 0.89
73.00%, ll=0.00000, gf=96.872, secs=31.0, GB=16.26, MB/s=525.33, GPUmem=0.89, 0.89
75.00%, ll=0.00000, gf=96.154, secs=32.5, GB=16.77, MB/s=515.33, GPUmem=0.89, 0.89
79.00%, ll=0.00000, gf=96.128, secs=33.9, GB=17.66, MB/s=520.81, GPUmem=0.89, 0.89
82.00%, ll=0.00000, gf=96.917, secs=35.0, GB=18.29, MB/s=523.05, GPUmem=0.89, 0.89
85.00%, ll=0.00000, gf=97.522, secs=36.1, GB=18.93, MB/s=524.42, GPUmem=0.89, 0.89
88.00%, ll=0.00000, gf=97.819, secs=37.3, GB=19.56, MB/s=524.26, GPUmem=0.89, 0.89
91.00%, ll=0.00000, gf=98.264, secs=38.5, GB=20.33, MB/s=528.29, GPUmem=0.89, 0.89
94.00%, ll=0.00000, gf=98.952, secs=39.5, GB=20.96, MB/s=530.32, GPUmem=0.89, 0.89
98.00%, ll=0.00000, gf=99.033, secs=40.8, GB=21.85, MB/s=535.43, GPUmem=0.89, 0.89
100.00%, ll=0.00000, gf=100.526, secs=41.5, GB=22.23, MB/s=535.70, GPUmem=0.89, 0.89
java.lang.RuntimeException: mismatched types for operator ~
  at BIDMat.FMat.$tilde(FMat.scala:1135)
  at BIDMach.models.KMeans$$anonfun$mergeModelPassFn$1.apply(KMeans.scala:95)
  at BIDMach.models.KMeans$$anonfun$mergeModelPassFn$1.apply(KMeans.scala:92)
  at scala.collection.immutable.Range.foreach(Range.scala:160)
  at BIDMach.models.KMeans.mergeModelPassFn(KMeans.scala:92)
  at BIDMach.ParLearner$.syncmodelsPass(Learner.scala:796)
  at BIDMach.ParLearner.retrain(Learner.scala:353)
  at BIDMach.ParLearnerF.retrain(Learner.scala:712)
  at BIDMach.ParLearnerF.train(Learner.scala:709)
  ... 112 elided
<console>:31: error: not found: value a
              val (mm8,opts8) = NMF.learnPar(a, 256)
                                             ^
<console>:32: error: value batchSize is not a member of Any
              opts8.batchSize = 5000
                    ^
<console>:33: error: value useGPU is not a member of Any
              opts8.useGPU=useGPU
                    ^
<console>:34: error: value npasses is not a member of Any
              opts8.npasses=2
                    ^
<console>:35: error: value nthreads is not a member of Any
              opts8.nthreads=Mat.hasCUDA
                    ^
<console>:36: error: value train is not a member of Any
              mm8.train
                  ^
<console>:39: error: not found: value a
              val (mm8,opts8) = NMF.learner(a, 128)
                                            ^
<console>:40: error: value batchSize is not a member of Any
              opts8.batchSize = 5000
                    ^
<console>:41: error: value useGPU is not a member of Any
              opts8.useGPU=useGPU
                    ^
<console>:42: error: value npasses is not a member of Any
              opts8.npasses=2
                    ^
<console>:43: error: value train is not a member of Any
              mm8.train
                  ^

**Comment by jcanny** [comment]
There was a bug in the type inference for multi-GPU KMeans. It should be fixed now.

**Comment by manjunaths** [comment]
Thank you for fixing this. Do the binary 1.0.3 versions that are provided for download have these fixes ? Do I need to compile the binaries myself ? In which case are there any documentation as starting point you would recommend ?

**Comment by jcanny** [comment]
Follow the current installation instructions. Basically  git clone and either run "getdevlibs.sh" or use maven.
