### ISSUE TITLE
*^ index out of bounds

### ISSUE THREAD

**Issue by jamesjia94** [BIDData/BIDMach#90]
scala> val a = rand(3,4)
a: BIDMat.FMat =
   0.40857   0.65735   0.18252   0.21719
   0.82198   0.38203   0.57885   0.25747
   0.13365  0.036090   0.57698   0.28741

scala> val b = rand(3,4)
b: BIDMat.FMat =
    0.44102    0.63252    0.38195   0.052384
    0.99267   0.053118  0.0094332   0.070619
    0.34677    0.82116    0.74243    0.42345

scala> a *^ b
java.lang.ArrayIndexOutOfBoundsException: 9
  at BIDMat.FMat.fDMultTHelper(FMat.scala:752)
  at BIDMat.FMat.multT(FMat.scala:778)
  at BIDMat.FMat.$times$up(FMat.scala:1253)
  ... 33 elided

**Comment by jamesjia94** [comment]
Moved issue to BIDMat
