### ISSUE TITLE
random forest computation error

### ISSUE THREAD

**Issue by christopher5106** [BIDData/BIDMach#93]
I've been using Random Forest a few times and I do not understand why I get some error. Once I've been able to stop the error by reducing the number of trees. 

For example you can re-generate some data : 

```
val params = drand(30,1)

0 until 50 map( i => {
  val fmat = FMat(drand(30,1000))
  saveMat("data%02d.fmat.lz4" format i, fmat);
  saveMat("label%02d.imat.lz4" format i, IMat(params ^* fmat) > 7)
})
```

and for example it will work well for ntrees=20 and ndepth=5, otherwise if I push the number of threes and the depth

```
val (mm,opts) = RandomForest.learner("data%02d.fmat.lz4","label%02d.imat.lz4")

opts.batchSize = 1000
opts.nend = 50
opts.depth =  50
opts.ncats = 2
opts.ntrees = 2000
opts.impurity = 0
opts.nsamps = 12
opts.nnodes = 50000
opts.nbits = 16
opts.gain = 0.001f

mm.train
```

I get a crash 

```
purity gain 0,1152, fraction impure 0,101, nnew 8,9, nnodes 249,4
pass=12
 4,00%, ll=0,00000, gf=1,582, secs=277,7, GB=0,07, MB/s= 0,27, GPUmem=0,466429
25,00%, ll=0,00000, gf=1,584, secs=282,7, GB=0,08, MB/s= 0,27, GPUmem=0,466429
48,00%, ll=0,00000, gf=1,586, secs=287,7, GB=0,08, MB/s= 0,27, GPUmem=0,466429
70,00%, ll=0,00000, gf=1,587, secs=292,6, GB=0,08, MB/s= 0,27, GPUmem=0,466429
92,00%, ll=0,00000, gf=1,589, secs=297,7, GB=0,08, MB/s= 0,27, GPUmem=0,466429
100,00%, ll=0,00000, gf=1,590, secs=299,1, GB=0,08, MB/s= 0,27, GPUmem=0,466429
java.lang.ArrayIndexOutOfBoundsException: 0
  at BIDMat.DenseMat$mcF$sp.ggReduceOpv$mcF$sp(DenseMat.scala:1113)
  at BIDMat.FMat.ffReduceOpv(FMat.scala:240)
  at BIDMat.SciFunctions$.sum(SciFunctions.scala:663)
  at BIDMat.SciFunctions$.sum(SciFunctions.scala:1020)
  at BIDMat.SciFunctions$._mean(SciFunctions.scala:1371)
  at BIDMat.SciFunctions$.mean(SciFunctions.scala:1327)
  at BIDMach.models.RandomForest.updatePass(RandomForest.scala:416)
  at BIDMach.updaters.Updater.updateM(Updater.scala:24)
  at BIDMach.Learner.nextPass(Learner.scala:162)
  at BIDMach.Learner.retrain(Learner.scala:82)
  at BIDMach.Learner.train(Learner.scala:69)
  ... 33 elided
```

And the same on a real data : 

```
val (mm,opts) = RandomForest.learner("mrh/data%02d.lz4","mrh/label%02d.lz4")
opts.batchSize = 10
opts.nend = 180
opts.regression = true
opts.depth =  4
opts.ntrees = 2500
opts.impurity = 0
opts.nsamps = 12
opts.nnodes = 50000
opts.nbits = 16
mm.train
pass= 0
 1,00%, ll=-2,16535, gf=0,688, secs=25,2, GB=0,02, MB/s= 0,98, GPUmem=0,509463
 2,00%, ll=-0,79978, gf=0,740, secs=46,9, GB=0,05, MB/s= 1,06, GPUmem=0,509463
 3,00%, ll=-1,48344, gf=0,762, secs=68,4, GB=0,07, MB/s= 1,09, GPUmem=0,509463
 4,00%, ll=-0,76151, gf=0,775, secs=89,6, GB=0,10, MB/s= 1,11, GPUmem=0,509463
 5,00%, ll=-2,05895, gf=0,784, secs=110,8, GB=0,12, MB/s= 1,12, GPUmem=0,509463
 6,00%, ll=-1,38516, gf=0,790, secs=131,8, GB=0,15, MB/s= 1,13, GPUmem=0,509463
 7,00%, ll=-1,43660, gf=0,796, secs=152,7, GB=0,17, MB/s= 1,14, GPUmem=0,509463
 8,00%, ll=-0,47004, gf=0,799, secs=173,9, GB=0,20, MB/s= 1,14, GPUmem=0,509463
 9,00%, ll=-1,91130, gf=0,802, secs=194,9, GB=0,22, MB/s= 1,14, GPUmem=0,509463
10,00%, ll=-0,76536, gf=0,805, secs=215,8, GB=0,25, MB/s= 1,15, GPUmem=0,509463
11,00%, ll=-1,46046, gf=0,807, secs=236,8, GB=0,27, MB/s= 1,15, GPUmem=0,509463
12,00%, ll=-0,62466, gf=0,808, secs=258,0, GB=0,30, MB/s= 1,15, GPUmem=0,509463
13,00%, ll=-1,14369, gf=0,810, secs=278,8, GB=0,32, MB/s= 1,16, GPUmem=0,509463
14,00%, ll=-1,12583, gf=0,811, secs=299,9, GB=0,35, MB/s= 1,16, GPUmem=0,509463
15,00%, ll=-2,51823, gf=0,811, secs=321,0, GB=0,37, MB/s= 1,16, GPUmem=0,509463
16,00%, ll=-1,23891, gf=0,812, secs=342,0, GB=0,40, MB/s= 1,16, GPUmem=0,509463
17,00%, ll=-0,47004, gf=0,814, secs=362,9, GB=0,42, MB/s= 1,16, GPUmem=0,509463
18,00%, ll=-1,35527, gf=0,814, secs=384,1, GB=0,45, MB/s= 1,16, GPUmem=0,509463
19,00%, ll=-1,46703, gf=0,814, secs=405,2, GB=0,47, MB/s= 1,16, GPUmem=0,509463
20,00%, ll=-1,39325, gf=0,815, secs=426,1, GB=0,50, MB/s= 1,16, GPUmem=0,509463
21,00%, ll=-0,83660, gf=0,816, secs=447,1, GB=0,52, MB/s= 1,16, GPUmem=0,509463
22,00%, ll=-0,86420, gf=0,816, secs=468,2, GB=0,55, MB/s= 1,16, GPUmem=0,509463
23,00%, ll=-1,94676, gf=0,817, secs=489,0, GB=0,57, MB/s= 1,17, GPUmem=0,509463
24,00%, ll=-1,56006, gf=0,817, secs=510,0, GB=0,59, MB/s= 1,17, GPUmem=0,509463
25,00%, ll=-1,41531, gf=0,818, secs=531,0, GB=0,62, MB/s= 1,17, GPUmem=0,509463
26,00%, ll=-1,75654, gf=0,818, secs=551,8, GB=0,64, MB/s= 1,17, GPUmem=0,509463
27,00%, ll=-0,14619, gf=0,819, secs=572,8, GB=0,67, MB/s= 1,17, GPUmem=0,509463
28,00%, ll=-2,64055, gf=0,819, secs=594,0, GB=0,69, MB/s= 1,17, GPUmem=0,509463
29,00%, ll=-0,50067, gf=0,819, secs=614,9, GB=0,72, MB/s= 1,17, GPUmem=0,509463
30,00%, ll=-0,35755, gf=0,819, secs=636,1, GB=0,74, MB/s= 1,17, GPUmem=0,509463
31,00%, ll=-0,60785, gf=0,819, secs=657,3, GB=0,77, MB/s= 1,17, GPUmem=0,509463
32,00%, ll=-2,43953, gf=0,819, secs=678,4, GB=0,79, MB/s= 1,17, GPUmem=0,509463
33,00%, ll=-1,17151, gf=0,819, secs=699,5, GB=0,82, MB/s= 1,17, GPUmem=0,509463
34,00%, ll=-1,09924, gf=0,819, secs=720,8, GB=0,84, MB/s= 1,17, GPUmem=0,509463
35,00%, ll=-1,08884, gf=0,819, secs=742,1, GB=0,87, MB/s= 1,17, GPUmem=0,509463
36,00%, ll=-1,21297, gf=0,819, secs=763,1, GB=0,89, MB/s= 1,17, GPUmem=0,509463
37,00%, ll=-0,46196, gf=0,819, secs=784,3, GB=0,92, MB/s= 1,17, GPUmem=0,509463
38,00%, ll=-1,37285, gf=0,819, secs=805,5, GB=0,94, MB/s= 1,17, GPUmem=0,509463
39,00%, ll=-0,82766, gf=0,819, secs=826,5, GB=0,97, MB/s= 1,17, GPUmem=0,509463
40,00%, ll=-2,05921, gf=0,819, secs=847,7, GB=0,99, MB/s= 1,17, GPUmem=0,509463
41,00%, ll=-1,69151, gf=0,819, secs=868,9, GB=1,02, MB/s= 1,17, GPUmem=0,509463
42,00%, ll=-1,84488, gf=0,820, secs=889,9, GB=1,04, MB/s= 1,17, GPUmem=0,509463
43,00%, ll=-1,58322, gf=0,820, secs=911,1, GB=1,07, MB/s= 1,17, GPUmem=0,509463
44,00%, ll=-0,27902, gf=0,819, secs=932,4, GB=1,09, MB/s= 1,17, GPUmem=0,509463
45,00%, ll=-2,58278, gf=0,820, secs=953,5, GB=1,11, MB/s= 1,17, GPUmem=0,509463
46,00%, ll=-0,57458, gf=0,820, secs=974,8, GB=1,14, MB/s= 1,17, GPUmem=0,509463
47,00%, ll=-0,81199, gf=0,819, secs=996,0, GB=1,16, MB/s= 1,17, GPUmem=0,509463
48,00%, ll=-0,92771, gf=0,820, secs=1017,1, GB=1,19, MB/s= 1,17, GPUmem=0,509463
49,00%, ll=-1,94653, gf=0,819, secs=1038,4, GB=1,21, MB/s= 1,17, GPUmem=0,509463
50,00%, ll=-1,58453, gf=0,819, secs=1059,9, GB=1,24, MB/s= 1,17, GPUmem=0,509463
51,00%, ll=-1,13746, gf=0,819, secs=1081,1, GB=1,26, MB/s= 1,17, GPUmem=0,509463
52,00%, ll=-0,69798, gf=0,819, secs=1102,6, GB=1,29, MB/s= 1,17, GPUmem=0,509463
53,00%, ll=-1,53548, gf=0,819, secs=1124,0, GB=1,31, MB/s= 1,17, GPUmem=0,509463
54,00%, ll=-0,18965, gf=0,819, secs=1145,0, GB=1,34, MB/s= 1,17, GPUmem=0,509463
55,00%, ll=-1,58877, gf=0,818, secs=1167,1, GB=1,36, MB/s= 1,17, GPUmem=0,509463
56,00%, ll=-0,50067, gf=0,818, secs=1189,5, GB=1,39, MB/s= 1,17, GPUmem=0,509463
57,00%, ll=-1,68442, gf=0,817, secs=1211,5, GB=1,41, MB/s= 1,17, GPUmem=0,509463
58,00%, ll=-1,68183, gf=0,816, secs=1234,0, GB=1,44, MB/s= 1,16, GPUmem=0,509463
59,00%, ll=-2,17178, gf=0,815, secs=1256,5, GB=1,46, MB/s= 1,16, GPUmem=0,509463
60,00%, ll=-0,91361, gf=0,815, secs=1279,0, GB=1,49, MB/s= 1,16, GPUmem=0,509463
61,00%, ll=-0,68067, gf=0,814, secs=1301,2, GB=1,51, MB/s= 1,16, GPUmem=0,509463
62,00%, ll=-1,80693, gf=0,813, secs=1323,7, GB=1,54, MB/s= 1,16, GPUmem=0,509463
63,00%, ll=-1,01691, gf=0,813, secs=1346,1, GB=1,56, MB/s= 1,16, GPUmem=0,509463
64,00%, ll=-1,63352, gf=0,812, secs=1368,1, GB=1,59, MB/s= 1,16, GPUmem=0,509463
65,00%, ll=-0,59990, gf=0,812, secs=1390,6, GB=1,61, MB/s= 1,16, GPUmem=0,509463
66,00%, ll=-1,54759, gf=0,811, secs=1413,0, GB=1,64, MB/s= 1,16, GPUmem=0,509463
67,00%, ll=-2,05585, gf=0,811, secs=1435,2, GB=1,66, MB/s= 1,16, GPUmem=0,509463
68,00%, ll=-1,43016, gf=0,810, secs=1457,8, GB=1,68, MB/s= 1,16, GPUmem=0,509463
69,00%, ll=-0,47215, gf=0,809, secs=1480,2, GB=1,71, MB/s= 1,15, GPUmem=0,509463
70,00%, ll=-1,75654, gf=0,809, secs=1502,6, GB=1,73, MB/s= 1,15, GPUmem=0,509463
71,00%, ll=-0,68669, gf=0,808, secs=1525,1, GB=1,76, MB/s= 1,15, GPUmem=0,509463
72,00%, ll=-1,68840, gf=0,808, secs=1547,6, GB=1,78, MB/s= 1,15, GPUmem=0,509463
73,00%, ll=-0,62466, gf=0,808, secs=1569,9, GB=1,81, MB/s= 1,15, GPUmem=0,509463
74,00%, ll=-1,14369, gf=0,807, secs=1592,5, GB=1,83, MB/s= 1,15, GPUmem=0,509463
75,00%, ll=-0,88783, gf=0,806, secs=1614,9, GB=1,86, MB/s= 1,15, GPUmem=0,509463
76,00%, ll=-2,15828, gf=0,806, secs=1637,2, GB=1,88, MB/s= 1,15, GPUmem=0,509463
77,00%, ll=-1,32767, gf=0,806, secs=1659,8, GB=1,91, MB/s= 1,15, GPUmem=0,509463
78,00%, ll=-0,85052, gf=0,805, secs=1682,5, GB=1,93, MB/s= 1,15, GPUmem=0,509463
79,00%, ll=-1,48685, gf=0,805, secs=1704,8, GB=1,96, MB/s= 1,15, GPUmem=0,509463
80,00%, ll=-1,46703, gf=0,804, secs=1727,4, GB=1,98, MB/s= 1,15, GPUmem=0,509463
81,00%, ll=-0,97582, gf=0,804, secs=1750,2, GB=2,01, MB/s= 1,15, GPUmem=0,509463
82,00%, ll=-1,25591, gf=0,803, secs=1772,6, GB=2,03, MB/s= 1,15, GPUmem=0,509463
83,00%, ll=-0,86420, gf=0,803, secs=1795,3, GB=2,06, MB/s= 1,15, GPUmem=0,509463
84,00%, ll=-1,93803, gf=0,802, secs=1818,0, GB=2,08, MB/s= 1,14, GPUmem=0,509463
85,00%, ll=-1,56708, gf=0,802, secs=1840,3, GB=2,11, MB/s= 1,14, GPUmem=0,509463
86,00%, ll=-1,40896, gf=0,802, secs=1863,0, GB=2,13, MB/s= 1,14, GPUmem=0,509463
87,00%, ll=-1,76445, gf=0,801, secs=1885,7, GB=2,16, MB/s= 1,14, GPUmem=0,509463
88,00%, ll=-0,14619, gf=0,801, secs=1908,0, GB=2,18, MB/s= 1,14, GPUmem=0,509463
89,00%, ll=-2,64055, gf=0,801, secs=1930,7, GB=2,21, MB/s= 1,14, GPUmem=0,509463
90,00%, ll=-0,33906, gf=0,800, secs=1953,4, GB=2,23, MB/s= 1,14, GPUmem=0,509463
91,00%, ll=-0,39638, gf=0,800, secs=1976,1, GB=2,25, MB/s= 1,14, GPUmem=0,509463
92,00%, ll=-0,73232, gf=0,799, secs=1998,4, GB=2,28, MB/s= 1,14, GPUmem=0,509463
93,00%, ll=-2,22290, gf=0,799, secs=2021,3, GB=2,30, MB/s= 1,14, GPUmem=0,509463
94,00%, ll=-1,00503, gf=0,799, secs=2044,1, GB=2,33, MB/s= 1,14, GPUmem=0,509463
95,00%, ll=-1,13746, gf=0,798, secs=2066,4, GB=2,35, MB/s= 1,14, GPUmem=0,509463
96,00%, ll=-1,19985, gf=0,798, secs=2089,2, GB=2,38, MB/s= 1,14, GPUmem=0,509463
97,00%, ll=-1,44092, gf=0,798, secs=2111,9, GB=2,40, MB/s= 1,14, GPUmem=0,509463
98,00%, ll=-0,19051, gf=0,797, secs=2134,5, GB=2,43, MB/s= 1,14, GPUmem=0,509463
99,00%, ll=-1,64309, gf=0,797, secs=2157,5, GB=2,45, MB/s= 1,14, GPUmem=0,509463
100,00%, ll=-0,59100, gf=0,796, secs=2180,6, GB=2,48, MB/s= 1,14, GPUmem=0,509463
purity gain 0,0000, fraction impure 1,000, nnew 0,0, nnodes 1,0
pass= 1
java.lang.NegativeArraySizeException
  at BIDMat.LMat$.apply(LMat.scala:952)
  at BIDMat.MatFunctions$.lzeros(MatFunctions.scala:1261)
  at BIDMach.models.SVec$.apply(RandomForest.scala:1324)
  at BIDMach.models.RandomForest.splittableNodes_thread(RandomForest.scala:867)
  at BIDMach.models.RandomForest$$anonfun$splittableNodes$1.apply(RandomForest.scala:859)
  at BIDMach.models.RandomForest$$anonfun$splittableNodes$1.apply(RandomForest.scala:858)
  at scala.collection.parallel.immutable.ParRange$ParRangeIterator.map2combiner(ParRange.scala:105)
  at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1053)
  at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
  at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
  at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
  at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
  at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1050)
  at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
  at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
  at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runSubtask(ForkJoinPool.java:1357)
  at scala.concurrent.forkjoin.ForkJoinPool.tryHelpStealer(ForkJoinPool.java:2253)
  at scala.concurrent.forkjoin.ForkJoinPool.awaitJoin(ForkJoinPool.java:2377)
  at scala.concurrent.forkjoin.ForkJoinTask.doJoin(ForkJoinTask.java:341)
  at scala.concurrent.forkjoin.ForkJoinTask.join(ForkJoinTask.java:673)
  at scala.collection.parallel.ForkJoinTasks$WrappedTask$class.sync(Tasks.scala:378)
  at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:443)
  at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:173)
  at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
  at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
  at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
  at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runSubtask(ForkJoinPool.java:1357)
  at scala.concurrent.forkjoin.ForkJoinPool.tryHelpStealer(ForkJoinPool.java:2253)
  at scala.concurrent.forkjoin.ForkJoinPool.awaitJoin(ForkJoinPool.java:2377)
  at scala.concurrent.forkjoin.ForkJoinTask.doJoin(ForkJoinTask.java:341)
  at scala.concurrent.forkjoin.ForkJoinTask.join(ForkJoinTask.java:673)
  at scala.collection.parallel.ForkJoinTasks$WrappedTask$class.sync(Tasks.scala:378)
  at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:443)
  at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:173)
  at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
  at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
  at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
  at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

This should not happen :( 
What are the mistakes I make ?

**Comment by jcanny** [comment]
Could you help us with basic info:
* What version of the code are you running?
* What machine/OS are you running?
* What kind of GPU is it? 

You've shown us only the lines before the crash in your first example, so we cant tell if the algorithm was behaving correctly until then. 

In your first example, its showing the ll as 0. i.e. there are no errors in the predictions. That's strange. Was that true in previous iterations? Please show everything from that execution. 

There are two unrelated errors that probably have to do with size. Could you find out where they happen, e.g. what are the maximum sizes work correctly? That's a good clue to which resources is exceeding its limit.

**Comment by christopher5106** [comment]
For the first execution, it is easy to reproduce because I gave you all the code to create the random data and the training. Execution is made on a Linux G2.2xlarge instance https://aws.amazon.com/ec2/instance-types/ or on a iMac. It is working ok for ntrees=20 and ndepth=5 but not for bigger values : 

```
mm.train
pass= 0
 4,00%, ll=-0,26900, gf=0,226, secs=3,6, GB=0,00, MB/s= 0,07, GPUmem=0,466429
25,00%, ll=-0,26900, gf=1,290, secs=7,0, GB=0,00, MB/s= 0,23, GPUmem=0,466429
48,00%, ll=-0,26900, gf=1,673, secs=10,2, GB=0,00, MB/s= 0,29, GPUmem=0,466429
70,00%, ll=-0,26900, gf=1,922, secs=13,2, GB=0,00, MB/s= 0,33, GPUmem=0,466429
92,00%, ll=-0,26900, gf=2,042, secs=16,4, GB=0,01, MB/s= 0,35, GPUmem=0,466429
100,00%, ll=-0,26900, gf=2,089, secs=17,2, GB=0,01, MB/s= 0,36, GPUmem=0,466429
purity gain 0,0276, fraction impure 1,000, nnew 2,0, nnodes 3,0
pass= 1
 4,00%, ll=-0,26900, gf=1,744, secs=21,1, GB=0,01, MB/s= 0,31, GPUmem=0,466429
25,00%, ll=-0,26900, gf=1,817, secs=24,7, GB=0,01, MB/s= 0,32, GPUmem=0,466429
48,00%, ll=-0,26900, gf=1,892, secs=28,1, GB=0,01, MB/s= 0,33, GPUmem=0,466429
70,00%, ll=-0,26900, gf=1,937, secs=31,6, GB=0,01, MB/s= 0,33, GPUmem=0,466429
92,00%, ll=-0,26900, gf=1,954, secs=35,5, GB=0,01, MB/s= 0,33, GPUmem=0,466429
100,00%, ll=-0,26900, gf=1,954, secs=36,8, GB=0,01, MB/s= 0,34, GPUmem=0,466429
purity gain 0,0302, fraction impure 1,000, nnew 4,0, nnodes 7,0
pass= 2
 4,00%, ll=-0,26000, gf=1,823, secs=39,9, GB=0,01, MB/s= 0,32, GPUmem=0,466429
25,00%, ll=-0,26000, gf=1,841, secs=44,0, GB=0,01, MB/s= 0,32, GPUmem=0,466429
48,00%, ll=-0,26000, gf=1,837, secs=48,5, GB=0,02, MB/s= 0,32, GPUmem=0,466429
70,00%, ll=-0,26000, gf=1,846, secs=52,7, GB=0,02, MB/s= 0,32, GPUmem=0,466429
92,00%, ll=-0,26000, gf=1,850, secs=57,0, GB=0,02, MB/s= 0,32, GPUmem=0,466429
100,00%, ll=-0,26000, gf=1,849, secs=58,4, GB=0,02, MB/s= 0,32, GPUmem=0,466429
purity gain 0,0416, fraction impure 1,000, nnew 8,0, nnodes 15,0
pass= 3
 4,00%, ll=-0,20700, gf=1,763, secs=61,8, GB=0,02, MB/s= 0,31, GPUmem=0,466429
25,00%, ll=-0,20700, gf=1,767, secs=66,3, GB=0,02, MB/s= 0,30, GPUmem=0,466429
48,00%, ll=-0,20700, gf=1,761, secs=71,2, GB=0,02, MB/s= 0,30, GPUmem=0,466429
70,00%, ll=-0,20700, gf=1,763, secs=75,8, GB=0,02, MB/s= 0,30, GPUmem=0,466429
92,00%, ll=-0,20700, gf=1,757, secs=80,7, GB=0,02, MB/s= 0,30, GPUmem=0,466429
100,00%, ll=-0,20700, gf=1,761, secs=81,9, GB=0,02, MB/s= 0,30, GPUmem=0,466429
purity gain 0,0728, fraction impure 1,000, nnew 15,3, nnodes 30,3
pass= 4
 4,00%, ll=-0,14500, gf=1,695, secs=85,6, GB=0,03, MB/s= 0,29, GPUmem=0,466429
25,00%, ll=-0,14500, gf=1,695, secs=90,5, GB=0,03, MB/s= 0,29, GPUmem=0,466429
48,00%, ll=-0,14500, gf=1,686, secs=95,9, GB=0,03, MB/s= 0,29, GPUmem=0,466429
70,00%, ll=-0,14500, gf=1,685, secs=100,8, GB=0,03, MB/s= 0,29, GPUmem=0,466429
92,00%, ll=-0,14500, gf=1,678, secs=106,1, GB=0,03, MB/s= 0,29, GPUmem=0,466429
100,00%, ll=-0,14500, gf=1,679, secs=107,5, GB=0,03, MB/s= 0,29, GPUmem=0,466429
purity gain 0,1087, fraction impure 0,985, nnew 25,5, nnodes 55,7
pass= 5
 4,00%, ll=-0,10100, gf=1,630, secs=111,4, GB=0,03, MB/s= 0,28, GPUmem=0,466429
25,00%, ll=-0,10100, gf=1,628, secs=116,6, GB=0,03, MB/s= 0,28, GPUmem=0,466429
48,00%, ll=-0,10100, gf=1,625, secs=121,8, GB=0,03, MB/s= 0,28, GPUmem=0,466429
70,00%, ll=-0,10100, gf=1,620, secs=127,3, GB=0,04, MB/s= 0,28, GPUmem=0,466429
92,00%, ll=-0,10100, gf=1,618, secs=132,6, GB=0,04, MB/s= 0,28, GPUmem=0,466429
100,00%, ll=-0,10100, gf=1,614, secs=134,5, GB=0,04, MB/s= 0,28, GPUmem=0,466429
purity gain 0,1358, fraction impure 0,908, nnew 35,6, nnodes 91,3
pass= 6
 4,00%, ll=-0,02400, gf=1,577, secs=138,2, GB=0,04, MB/s= 0,27, GPUmem=0,466429
25,00%, ll=-0,02400, gf=1,576, secs=143,6, GB=0,04, MB/s= 0,27, GPUmem=0,466429
48,00%, ll=-0,02400, gf=1,574, secs=149,0, GB=0,04, MB/s= 0,27, GPUmem=0,466429
70,00%, ll=-0,02400, gf=1,573, secs=154,4, GB=0,04, MB/s= 0,27, GPUmem=0,466429
92,00%, ll=-0,02400, gf=1,572, secs=159,8, GB=0,04, MB/s= 0,27, GPUmem=0,466429
100,00%, ll=-0,02400, gf=1,569, secs=161,6, GB=0,04, MB/s= 0,27, GPUmem=0,466429
purity gain 0,1481, fraction impure 0,764, nnew 41,4, nnodes 132,7
pass= 7
 4,00%, ll=-0,00100, gf=1,548, secs=164,5, GB=0,04, MB/s= 0,27, GPUmem=0,466429
25,00%, ll=-0,00100, gf=1,546, secs=170,1, GB=0,05, MB/s= 0,26, GPUmem=0,466429
48,00%, ll=-0,00100, gf=1,544, secs=175,7, GB=0,05, MB/s= 0,26, GPUmem=0,466429
70,00%, ll=-0,00100, gf=1,543, secs=181,2, GB=0,05, MB/s= 0,26, GPUmem=0,466429
92,00%, ll=-0,00100, gf=1,542, secs=186,7, GB=0,05, MB/s= 0,26, GPUmem=0,466429
100,00%, ll=-0,00100, gf=1,543, secs=188,1, GB=0,05, MB/s= 0,26, GPUmem=0,466429
purity gain 0,1482, fraction impure 0,590, nnew 39,7, nnodes 172,4
pass= 8
 4,00%, ll=0,00000, gf=1,523, secs=191,3, GB=0,05, MB/s= 0,26, GPUmem=0,466429
25,00%, ll=0,00000, gf=1,527, secs=196,3, GB=0,05, MB/s= 0,26, GPUmem=0,466429
48,00%, ll=0,00000, gf=1,525, secs=202,0, GB=0,05, MB/s= 0,26, GPUmem=0,466429
70,00%, ll=0,00000, gf=1,529, secs=207,0, GB=0,05, MB/s= 0,26, GPUmem=0,466429
92,00%, ll=0,00000, gf=1,527, secs=212,7, GB=0,06, MB/s= 0,26, GPUmem=0,466429
100,00%, ll=0,00000, gf=1,528, secs=214,1, GB=0,06, MB/s= 0,26, GPUmem=0,466429
purity gain 0,1419, fraction impure 0,404, nnew 31,7, nnodes 204,2
pass= 9
 4,00%, ll=0,00000, gf=1,513, secs=217,0, GB=0,06, MB/s= 0,26, GPUmem=0,466429
25,00%, ll=0,00000, gf=1,516, secs=222,1, GB=0,06, MB/s= 0,26, GPUmem=0,466429
48,00%, ll=0,00000, gf=1,519, secs=227,1, GB=0,06, MB/s= 0,26, GPUmem=0,466429
70,00%, ll=0,00000, gf=1,522, secs=232,2, GB=0,06, MB/s= 0,26, GPUmem=0,466429
92,00%, ll=0,00000, gf=1,520, secs=237,9, GB=0,06, MB/s= 0,26, GPUmem=0,466429
100,00%, ll=0,00000, gf=1,522, secs=239,3, GB=0,06, MB/s= 0,26, GPUmem=0,466429
purity gain 0,1292, fraction impure 0,245, nnew 20,8, nnodes 225,0
pass=10
 4,00%, ll=0,00000, gf=1,514, secs=241,2, GB=0,06, MB/s= 0,26, GPUmem=0,466429
25,00%, ll=0,00000, gf=1,517, secs=246,2, GB=0,06, MB/s= 0,26, GPUmem=0,466429
48,00%, ll=0,00000, gf=1,516, secs=251,9, GB=0,06, MB/s= 0,26, GPUmem=0,466429
70,00%, ll=0,00000, gf=1,518, secs=257,1, GB=0,07, MB/s= 0,26, GPUmem=0,466429
92,00%, ll=0,00000, gf=1,521, secs=262,2, GB=0,07, MB/s= 0,26, GPUmem=0,466429
100,00%, ll=0,00000, gf=1,522, secs=263,7, GB=0,07, MB/s= 0,26, GPUmem=0,466429
purity gain 0,1170, fraction impure 0,130, nnew 11,5, nnodes 236,4
pass=11
 4,00%, ll=0,00000, gf=1,514, secs=265,6, GB=0,07, MB/s= 0,26, GPUmem=0,466429
25,00%, ll=0,00000, gf=1,517, secs=270,6, GB=0,07, MB/s= 0,26, GPUmem=0,466429
48,00%, ll=0,00000, gf=1,520, secs=275,6, GB=0,07, MB/s= 0,26, GPUmem=0,466429
70,00%, ll=0,00000, gf=1,523, secs=280,6, GB=0,07, MB/s= 0,26, GPUmem=0,466429
92,00%, ll=0,00000, gf=1,525, secs=285,7, GB=0,07, MB/s= 0,26, GPUmem=0,466429
100,00%, ll=0,00000, gf=1,523, secs=287,8, GB=0,07, MB/s= 0,26, GPUmem=0,466429
java.lang.ArrayIndexOutOfBoundsException: 0
  at BIDMat.DenseMat$mcF$sp.ggReduceOpv$mcF$sp(DenseMat.scala:1113)
  at BIDMat.FMat.ffReduceOpv(FMat.scala:240)
  at BIDMat.SciFunctions$.sum(SciFunctions.scala:667)
  at BIDMat.SciFunctions$.sum(SciFunctions.scala:1024)
  at BIDMat.SciFunctions$._mean(SciFunctions.scala:1375)
  at BIDMat.SciFunctions$.mean(SciFunctions.scala:1331)
  at BIDMach.models.RandomForest.updatePass(RandomForest.scala:416)
  at BIDMach.updaters.Updater.updateM(Updater.scala:24)
  at BIDMach.Learner.nextPass(Learner.scala:162)
  at BIDMach.Learner.retrain(Learner.scala:82)
  at BIDMach.Learner.train(Learner.scala:69)
  ... 33 elided

```

**Comment by jcanny** [comment]
OK, the error was happening when one or more trees close off at the current level. i.e. when they have no more nodes that can be split. 

I changed the code to deal with that case. It should be working now.

**Comment by jcanny** [comment]
PS, note that regression forests still expect integer targets. You should scale a continuous target value to a range 0..k. The predictions will be continuous, and the intention is they should get scaled back to the original range.

**Comment by christopher5106** [comment]
Is it for both errors ?

Shall I simply pull the BIDMach repo ?

Thanks :)))

Christopher Bourez
06 17 17 50 60

**Comment by jcanny** [comment]
Yes, both issues should be fixed. you can either pull and compile or do getdevlibs.sh

**Comment by christopher5106** [comment]
Great thanks, I give a try

Christopher Bourez
06 17 17 50 60

**Comment by christopher5106** [comment]
Works !!!
