### ISSUE TITLE
/lib/libbidmatmkl-linux-x86_64.so Not found But in Library Path

### ISSUE THREAD

**Issue by asevans48** [BIDData/BIDMach#98]
I added the library path to my eclipse project for the above. Both .so files exist but I am getting the following from the executables I downloaded from your website. Interestingly, I can vi into the file.
```

 No resource found with name '/lib/libbidmatmkl-linux-x86_64.so'
	at jcuda.LibUtils.loadLibraryResource(LibUtils.java:149)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:83)
	at edu.berkeley.bid.VSL.<clinit>(VSL.java:6)
	at BIDMat.SciFunctions$.<init>(SciFunctions.scala:25)
	at BIDMat.SciFunctions$.<clinit>(SciFunctions.scala)
	at com.hygenics.matrixtests.BidMatTest.<init>(BidMatTest.scala:15)
	at com.hygenics.matrixtests.Driver$.main(BidMatTest.scala:50)
	at com.hygenics.matrixtests.Driver.main(BidMatTest.scala)
Stack trace from the attempt to load the library as a file:
java.lang.UnsatisfiedLinkError: /CORRECT/PATH/TO/BidMach/BIDMach_1.0.3-linux-x86_64/lib/libbidmatmkl-linux-x86_64.so: libiomp5.so: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jcuda.LibUtils.loadLibrary(LibUtils.java:94)
	at edu.berkeley.bid.VSL.<clinit>(VSL.java:6)
	at BIDMat.SciFunctions$.<init>(SciFunctions.scala:25)
	at BIDMat.SciFunctions$.<clinit>(SciFunctions.scala)
	at com.hygenics.matrixtests.BidMatTest.<init>(BidMatTest.scala:15)
	at com.hygenics.matrixtests.Driver$.main(BidMatTest.scala:50)
	at com.hygenics.matrixtests.Driver.main(BidMatTest.scala)

	at jcuda.LibUtils.loadLibrary(LibUtils.java:126)
	at edu.berkeley.bid.VSL.<clinit>(VSL.java:6)
	at BIDMat.SciFunctions$.<init>(SciFunctions.scala:25)
	at BIDMat.SciFunctions$.<clinit>(SciFunctions.scala)
	at com.hygenics.matrixtests.BidMatTest.<init>(BidMatTest.scala:15)
	at com.hygenics.matrixtests.Driver$.main(BidMatTest.scala:50)
	at com.hygenics.matrixtests.Driver.main(BidMatTest.scala)

```

**Comment by asevans48** [comment]
Also, I have loaded a version on windows in STS Tools suite x64 with my 64 bit operating system, added the lib path to my path, added cuda to my path, added both /lib paths to my STS.ini under the appropriate java file path and receive the following.
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load the native library.
Error while loading native library "bidmatmkl-windows-x86" with base name "bidmatmkl"
Operating system name: Windows 10
Architecture         : x86
Architecture bit size: 32
```

**Comment by jcanny** [comment]
Native code/path problems are always tricky to debug on other systems. We would need more information to debug yours. Please always include the OS type and version, and how you downloaded BIDMach, how you attempting to set the path in eclipse etc.

The easiest way to access native code in eclipse is to add the .so files as native library dependencies inside the .jar files listed in the project's. YOu'll need to do *five* of these. One each for bidmat cpu and gpu libraries, one each for bidmach cpu and gpu, and one for libiomp5.so which is Intel's threading library which the cpu libraries depend on. 

Sorry we cant make this cleaner. The libiomp5 dependency causes 90% of path problems but we cant remove it without removing OMP support (since Apple doesnt have that support any more), and there isnt another platform-independent CPU threading solution. It unfortunately cant be statically linked without causing collisions between the bidmat and bidmach libraries.
